### ISSUE TITLE
Access account as user or admin (2 days)

### ISSUE THREAD

**Issue by aebreneman** [bcm27/ClubBudgeting#12]
As a user, I want a way to access my account as either a club leader or administrator to be able to utilize this program. This will be a combination of C# code and a table or two in the database that utilize encoding for safe password storage. The second table or part of the table will contain usernames or emails for login and what type of user they are - either an admin or a club owner. The types will be stored in an enum table that can be updated with different account types. These account types will be restricted based on what each can access through C# code. Testing for this PBI will include trying to create an account, logging in with an account that has an invalid password/username, and trying to access admin only functionality as a club leader.

**Comment by SoftwareInventions** [comment]
This is a little more complete than the two I just commented on -- good.

**Comment by bcm27** [comment]
We now have the ability to log in as both as user or a admin, doing so will bring up the appropriate screen. Invalid credentials will throw an error and a message box prompting you to try again.
