### ISSUE TITLE
Admin database (2 days)

### ISSUE THREAD

**Issue by SamuelPMeier** [bcm27/ClubBudgeting#14]
As an administrator, I want an easy way to keep track of each club's current budget, debt, and list of purchases so I can better keep track of their budget. For this PBI, a database containing clubs and their budgets will suffice. The database will be in MySQL and will be based off of a "Club Funds" database that was completed in last semester's Database Management course - it will be edited to suit the needs of this project. This PBI will display data from the budget, debt and purchase tables in the database. This can be tested through automated C# and MySQL code to test the integrity of the database. There will be automated tests to check that the budget, debt, and purchase tables can get data added to them and display correctly.

**Comment by SoftwareInventions** [comment]
Again, better, but if you're going to implement this, you need a list of what tables you'll add/change, and at least a brief list of automated test cases you want to build for the DB.

**Comment by bcm27** [comment]
This goal is accomplished on the admin screen.
