### ISSUE TITLE
Admin add purchase and returns (1 day)

### ISSUE THREAD

**Issue by SamuelPMeier** [bcm27/ClubBudgeting#15]
As an administrator, I want an easy way to subtract purchases from the club's budget and add returns back into the club’s budget so each club has an updated budget to view. For this PBI, the administrator will have a form that they can enter amounts to subtract or add to a club's budget. It will then update in the main database. The form will have fields for subtracting from a budget (for purchases) and adding to a budget (for returns). There will be tables in the main database to hold the total budget amount for each club. The admin will be able to edit those tables for returns or purchases. This can be tested through C# SQL statements by adding subtracting and removing various categories. We will test the boundaries of the budgets by subtracting more than what is in the budget - that situation should throw an error. We will hand test the form to check and ensure that it updates the database correctly and calculates the correct numbers. The form’s error handling will be done in C# and will not allow numbers to be entered that go beyond the edge of the budget for each club, i.e. subtracting a purchase that is bigger than the entire budget.

**Comment by SoftwareInventions** [comment]
Better, but how about some detail on that form?  Fields, requirements, error checks?

And, review issues for grammar, spelling, etc.  There's some low-hanging fruit in that area here.
