### ISSUE TITLE
Submitting budget proposal (1 day)

### ISSUE THREAD

**Issue by bcm27** [bcm27/ClubBudgeting#6]
As a club leader, I want to be able to submit my club budget proposal for an easy submission process. The club budget proposal will reside in the form of an excel sheet, limiting the user to under 10 different categories for expenses within their budget. This excel sheet will be exportable to the administrator and will be stored in the database. Once done the administrator will be able to check which clubs have submitted their proposals and which have not. Testing will be done in the form of manually checking data integrity with the exported excel document and some automated testing with size limitations both exceeding and attempts at changing/submitting non existing data.

[EXAMPLE.xlsx](https://github.com/bcm27/ClubBudgeting/files/904145/EXAMPLE.xlsx)

**Comment by SoftwareInventions** [comment]
How about a sample Excel doc attached to this?
